# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [5]:

path = ("../output_data/city_weather.csv")
df = pd.read_csv(path)
df.head()

,Unnamed: 0,cities,temp(f),latitude,longitude,humidity,cloudiness,wind_speed
0,0,leningradskiy,35.28,69.3833,178.4167,93.0,99.0,13.60
1,1,dikson,40.60,73.5069,80.5464,99.0,100.0,1.70
2,2,constantine,90.81,36.3650,6.6147,33.0,75.0,14.97
3,3,butaritari,83.19,3.0707,172.7902,70.0,36.0,9.73
4,4,thompson,48.36,55.7435,-97.8558,93.0,20.0,0.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
# Store latitude and longitude in locations
locations = df[["latitude", "longitude"]]
humidity = df["humidity"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [11]:
hotel_df = pd.DataFrame(df[(df['temp(f)']<80) & (df['temp(f)']>70) & (df['humidity']<50)])

hotel_df

,Unnamed: 0,cities,temp(f),latitude,longitude,humidity,cloudiness,wind_speed
23,23,laukaa,76.08,58.7372,29.8453,41.0,43.0,11.52
49,49,nikolskoye,72.64,59.7035,30.7861,47.0,63.0,8.46
64,64,medea,72.05,36.2642,2.7539,19.0,80.0,9.04
130,130,gerede,79.25,40.8008,32.1969,23.0,0.0,12.82
170,170,xining,72.77,36.6167,101.7667,41.0,60.0,7.54
204,204,tsumeb,74.44,-19.2333,17.7167,18.0,0.0,15.19
208,208,caiaponia,74.32,-16.9567,-51.8103,31.0,16.0,6.55
213,213,ulaanbaatar,75.33,47.9077,106.8832,33.0,20.0,4.47
229,229,saskylakh,78.44,71.9167,114.0833,37.0,45.0,7.92
288,288,hohhot,75.49,40.8106,111.6522,31.0,0.0,13.42
310,310,makaryev,79.56,57.8797,43.8069,39.0,94.0,9.93
334,334,marrakesh,78.87,31.6315,-8.0083,41.0,0.0,5.75
391,391,manyana,71.92,-23.4000,21.7167,17.0,0.0,7.58
426,426,vanavara,72.75,60.3400,102.2797,45.0,100.0,6.44
454,454,nzega,72.91,-2.4790,29.5564,33.0,88.0,6.73
502,502,udachnyy,77.70,66.4167,112.4000,39.0,1.0,2.82
514,514,sayyan,71.92,15.1718,44.3244,43.0,91.0,3.94
521,521,hami,76.51,42.8000,93.4500,30.0,46.0,10.69
525,525,ust-koksa,71.67,50.2696,85.6108,46.0,55.0,6.73
577,577,warmbad,78.39,-28.4500,18.7333,12.0,0.0,5.55
578,578,bulawayo,72.64,-20.1500,28.5833,23.0,0.0,6.17

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [12]:
hotel_df['Hotel Name'] = ""
#hotel_df['City'] = ""
#hotel_df['Country'] = ""
hotel_df['compound_code'] = ""
hotel_df

,Unnamed: 0,cities,temp(f),latitude,longitude,humidity,cloudiness,wind_speed,Hotel Name,compound_code
23,23,laukaa,76.08,58.7372,29.8453,41.0,43.0,11.52,,
49,49,nikolskoye,72.64,59.7035,30.7861,47.0,63.0,8.46,,
64,64,medea,72.05,36.2642,2.7539,19.0,80.0,9.04,,
130,130,gerede,79.25,40.8008,32.1969,23.0,0.0,12.82,,
170,170,xining,72.77,36.6167,101.7667,41.0,60.0,7.54,,
204,204,tsumeb,74.44,-19.2333,17.7167,18.0,0.0,15.19,,
208,208,caiaponia,74.32,-16.9567,-51.8103,31.0,16.0,6.55,,
213,213,ulaanbaatar,75.33,47.9077,106.8832,33.0,20.0,4.47,,
229,229,saskylakh,78.44,71.9167,114.0833,37.0,45.0,7.92,,
288,288,hohhot,75.49,40.8106,111.6522,31.0,0.0,13.42,,
310,310,makaryev,79.56,57.8797,43.8069,39.0,94.0,9.93,,
334,334,marrakesh,78.87,31.6315,-8.0083,41.0,0.0,5.75,,
391,391,manyana,71.92,-23.4000,21.7167,17.0,0.0,7.58,,
426,426,vanavara,72.75,60.3400,102.2797,45.0,100.0,6.44,,
454,454,nzega,72.91,-2.4790,29.5564,33.0,88.0,6.73,,
502,502,udachnyy,77.70,66.4167,112.4000,39.0,1.0,2.82,,
514,514,sayyan,71.92,15.1718,44.3244,43.0,91.0,3.94,,
521,521,hami,76.51,42.8000,93.4500,30.0,46.0,10.69,,
525,525,ust-koksa,71.67,50.2696,85.6108,46.0,55.0,6.73,,
577,577,warmbad,78.39,-28.4500,18.7333,12.0,0.0,5.55,,
578,578,bulawayo,72.64,-20.1500,28.5833,23.0,0.0,6.17,,

In [13]:
# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["latitude"]
    lng = row["longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    #     print the name_address url, avoid doing for public github repos in order to avoid exposing key
    #     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        hotel_df.loc[index, "compound_code"] = name_address["results"][0]["plus_code"]["compound_code"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
hotel_df

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

,Unnamed: 0,cities,temp(f),latitude,longitude,humidity,cloudiness,wind_speed,Hotel Name,compound_code
23,23,laukaa,76.08,58.7372,29.8453,41.0,43.0,11.52,U Lysoy Gory Hotel,"PVP7+G6 Luga, Leningrad Oblast, Russia"
49,49,nikolskoye,72.64,59.7035,30.7861,47.0,63.0,8.46,Tourist House - Sablino,"MQ6H+4C Ul'yanovka, Leningrad Oblast, Russia"
64,64,medea,72.05,36.2642,2.7539,19.0,80.0,9.04,Hôtel M'Sallah,"7Q68+Q6 Médéa, Algeria"
130,130,gerede,79.25,40.8008,32.1969,23.0,0.0,12.82,Hotel Konuk,"Q6W4+29 Gerede/Bolu, Turkey"
170,170,xining,72.77,36.6167,101.7667,41.0,60.0,7.54,Super Leisure Hotel,"JPQV+3J Chengxi District, Xining, Qinghai, China"
204,204,tsumeb,74.44,-19.2333,17.7167,18.0,0.0,15.19,TeaterHuis Guest House,"QP39+RW Tsumeb, Namibia"
208,208,caiaponia,74.32,-16.9567,-51.8103,31.0,16.0,6.55,HOTEL PALACE AVENIDA & CAIAPÓ TURISMO,"25QM+3Q Setor Nova Caiaponia, Caiapônia - GO, ..."
213,213,ulaanbaatar,75.33,47.9077,106.8832,33.0,20.0,4.47,The Blue Sky Hotel and Tower,"WW89+HC Ulaanbaatar, Mongolia"
229,229,saskylakh,78.44,71.9167,114.0833,37.0,45.0,7.92,,
288,288,hohhot,75.49,40.8106,111.6522,31.0,0.0,13.42,Sheraton Hohhot Hotel,"RMGC+24 Xincheng District, Hohhot, Hohhot, Inn..."
310,310,makaryev,79.56,57.8797,43.8069,39.0,94.0,9.93,Postoyalyy Dvor,"VRG3+PC Makaryev, Kostroma Oblast, Russia"
334,334,marrakesh,78.87,31.6315,-8.0083,41.0,0.0,5.75,Novotel Marrakech Hivernage,"JXFX+42 Marrakesh, Morocco"
391,391,manyana,71.92,-23.4000,21.7167,17.0,0.0,7.58,,
426,426,vanavara,72.75,60.3400,102.2797,45.0,100.0,6.44,,
454,454,nzega,72.91,-2.4790,29.5564,33.0,88.0,6.73,Ubumwe Center Kigeme Ltd,"GHHG+PX Karama, Rwanda"
502,502,udachnyy,77.70,66.4167,112.4000,39.0,1.0,2.82,Severnoye Siyaniye,"C835+WM Udachny, Sakha Republic, Russia"
514,514,sayyan,71.92,15.1718,44.3244,43.0,91.0,3.94,متنزه و بحيرة سيان,"58PH+J3 Beit Al-Hamdani, Yemen"
521,521,hami,76.51,42.8000,93.4500,30.0,46.0,10.69,Laoyutang Resort,
525,525,ust-koksa,71.67,50.2696,85.6108,46.0,55.0,6.73,Uymonskaya Dolina,"7JC7+3M Ust'-Koksa, Altai Republic, Russia"
577,577,warmbad,78.39,-28.4500,18.7333,12.0,0.0,5.55,,
578,578,bulawayo,72.64,-20.1500,28.5833,23.0,0.0,6.17,4 On Housman Backpackers,

In [14]:
hotel_df[["compound_code","City","Country"]] = hotel_df["compound_code"].str.split(expand=True)
hotel_df['City'] = hotel_df['City'].str.rstrip(',')

hotel_df

ValueError: Columns must be same length as key

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["latitude", "longitude"]]

In [ ]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig